name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'npm'  # Removed to avoid lock file errors

      # Use npm install instead of npm ci since there's no lock file
      - name: Install dependencies
        run: npm install
        working-directory: ./GitHub-actions.git # change to the actual location of package.json

      - name: Build the project (if applicable)
        run: npm run build --if-present

      - name: Run tests
        run: npm test
